name: 'incr_stream'

config-version: 2
version: '0.0.1'

profile: 'my-snowflake-db'

model-paths: ["models"]
macro-paths: ["macros"]

docs-paths: ["docs"]

models:
  incr_stream:
    dwh:
      +schema: DWH
    stg:
      +schema: STG

vars:
  # default number of fake clients to add
  nb_clients: 30