version: 2

models:
  - name: conso_client_quoted
    description: "Test model for incremental_stream with quoted/special column names"
    columns:
      - name: id
        tests:
          - not_null
          - unique
    tests:
      - dbt_utils.equality:
          compare_model: ref('conso_client_quoted_incr')
