name: 'incr_stream_integration_test'

config-version: 2
version: '0.0.1'

profile: 'my-snowflake-db'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
docs-paths: ["docs"]

models:
  incr_stream_integration_test:
    dwh_multiple_streams:
      +schema: DWH
    dwh_insert:
      +schema: DWH
    dwh_source:
      +schema: DWH
    dwh_ref:
      +schema: DWH
    dwh_dyn:
      +schema: DWH
    stg:
      +schema: STG

vars:
  # default number of fake clients to add
  nb_clients: 30
